import 'cpu.dart';

class CpuTable {
  CPU _cpu;
  Map<int, List> _table;
  CpuTable(this._cpu) {
    // Operation code: [Addressing mode, instruction, size, cycles]
    var a = _cpu.addressing;
    var ins = _cpu.instruction;
    _table = {
      0x69: [a.immediate, ins.adc, 2, 2],
      0x65: [a.zeroPage, ins.adc, 2, 3],
      0x75: [a.zeroPageX, ins.adc, 2, 4],
      0x6d: [a.absolute, ins.adc, 3, 4],
      0x7d: [a.absoluteX, ins.adc, 3, 4],
      0x79: [a.absoluteY, ins.adc, 3, 4],
      0x61: [a.indirectX, ins.adc, 2, 6],
      0x71: [a.indirectY, ins.adc, 2, 5],
      0x29: [a.immediate, ins.and, 2, 2],
      0x25: [a.zeroPage, ins.and, 2, 3],
      0x35: [a.zeroPageX, ins.and, 2, 4],
      0x2d: [a.absolute, ins.and, 3, 4],
      0x3d: [a.absoluteX, ins.and, 3, 4],
      0x39: [a.absoluteY, ins.and, 3, 4],
      0x21: [a.indirectX, ins.and, 2, 6],
      0x31: [a.indirectY, ins.and, 2, 5],
      0x0a: [a.accumulator, ins.asl, 1, 2],
      0x06: [a.zeroPage, ins.asl, 2, 5],
      0x16: [a.zeroPageX, ins.asl, 2, 6],
      0x0e: [a.absolute, ins.asl, 3, 6],
      0x1e: [a.absoluteX, ins.asl, 3, 7],
      0x24: [a.zeroPage, ins.bit, 2, 3],
      0x2c: [a.absolute, ins.bit, 3, 4],
      0x10: [a.relative, ins.bpl, 2, 2],
      0x30: [a.relative, ins.bmi, 2, 2],
      0x50: [a.relative, ins.bvc, 2, 2],
      0x70: [a.relative, ins.bvs, 2, 2],
      0x90: [a.relative, ins.bcc, 2, 2],
      0xb0: [a.relative, ins.bcs, 2, 2],
      0xd0: [a.relative, ins.bne, 2, 2],
      0xf0: [a.relative, ins.beq, 2, 2],
      0x00: [a.implicit, ins.brk, 1, 7],
      0xc9: [a.immediate, ins.cmp, 2, 2],
      0xc5: [a.zeroPage, ins.cmp, 2, 3],
      0xd5: [a.zeroPageX, ins.cmp, 2, 4],
      0xcd: [a.absolute, ins.cmp, 3, 4],
      0xdd: [a.absoluteX, ins.cmp, 3, 4],
      0xd9: [a.absoluteY, ins.cmp, 3, 4],
      0xc1: [a.indirectX, ins.cmp, 2, 6],
      0xd1: [a.indirectY, ins.cmp, 2, 5],
      0xe0: [a.immediate, ins.cpx, 2, 2],
      0xe4: [a.zeroPage, ins.cpx, 2, 3],
      0xec: [a.absolute, ins.cpx, 3, 4],
      0xc0: [a.immediate, ins.cpy, 2, 2],
      0xc4: [a.zeroPage, ins.cpy, 2, 3],
      0xcc: [a.absolute, ins.cpy, 3, 4],
      0xc6: [a.zeroPage, ins.dec, 2, 5],
      0xd6: [a.zeroPageX, ins.dec, 2, 6],
      0xce: [a.absolute, ins.dec, 3, 6],
      0xde: [a.absoluteX, ins.dec, 3, 7],
      0x49: [a.immediate, ins.eor, 2, 2],
      0x45: [a.zeroPage, ins.eor, 2, 3],
      0x55: [a.zeroPageX, ins.eor, 2, 4],
      0x4d: [a.absolute, ins.eor, 3, 4],
      0x5d: [a.absoluteX, ins.eor, 3, 4],
      0x59: [a.absoluteY, ins.eor, 3, 4],
      0x41: [a.indirectX, ins.eor, 2, 6],
      0x51: [a.indirectY, ins.eor, 2, 5],
      0x18: [a.implicit, ins.clc, 1, 2],
      0x38: [a.implicit, ins.sec, 1, 2],
      0x58: [a.implicit, ins.cli, 1, 2],
      0x78: [a.implicit, ins.sei, 1, 2],
      0xb8: [a.implicit, ins.clv, 1, 2],
      0xd8: [a.implicit, ins.cld, 1, 2],
      0xf8: [a.implicit, ins.sed, 1, 2],
      0xe6: [a.zeroPage, ins.inc, 2, 5],
      0xf6: [a.zeroPageX, ins.inc, 2, 6],
      0xee: [a.absolute, ins.inc, 3, 6],
      0xfe: [a.absoluteX, ins.inc, 3, 7],
      0x4c: [a.absolute, ins.jmp, 3, 3],
      0x6c: [a.indirect, ins.jmp, 3, 5],
      0x20: [a.absolute, ins.jsr, 3, 6],
      0xa9: [a.immediate, ins.lda, 2, 2],
      0xa5: [a.zeroPage, ins.lda, 2, 3],
      0xb5: [a.zeroPageX, ins.lda, 2, 4],
      0xad: [a.absolute, ins.lda, 3, 4],
      0xbd: [a.absoluteX, ins.lda, 3, 4],
      0xb9: [a.absoluteY, ins.lda, 3, 4],
      0xa1: [a.indirectX, ins.lda, 2, 6],
      0xb1: [a.indirectY, ins.lda, 2, 5],
      0xa2: [a.immediate, ins.ldx, 2, 2],
      0xa6: [a.zeroPage, ins.ldx, 2, 3],
      0xb6: [a.zeroPageY, ins.ldx, 2, 4],
      0xae: [a.absolute, ins.ldx, 3, 4],
      0xbe: [a.absoluteY, ins.ldx, 3, 4],
      0xa0: [a.immediate, ins.ldy, 2, 2],
      0xa4: [a.zeroPage, ins.ldy, 2, 3],
      0xb4: [a.zeroPageX, ins.ldy, 2, 4],
      0xac: [a.absolute, ins.ldy, 3, 4],
      0xbc: [a.absoluteX, ins.ldy, 3, 4],
      0x4a: [a.accumulator, ins.lsr, 1, 2],
      0x46: [a.zeroPage, ins.lsr, 2, 5],
      0x56: [a.zeroPageX, ins.lsr, 2, 6],
      0x4e: [a.absolute, ins.lsr, 3, 6],
      0x5e: [a.absoluteX, ins.lsr, 3, 7],
      0xea: [a.implicit, ins.nop, 1, 2],
      0x09: [a.immediate, ins.ora, 2, 2],
      0x05: [a.zeroPage, ins.ora, 2, 3],
      0x15: [a.zeroPageX, ins.ora, 2, 4],
      0x0d: [a.absolute, ins.ora, 3, 4],
      0x1d: [a.absoluteX, ins.ora, 3, 4],
      0x19: [a.absoluteY, ins.ora, 3, 4],
      0x01: [a.indirectX, ins.ora, 2, 6],
      0x11: [a.indirectY, ins.ora, 2, 5],
      0xaa: [a.implicit, ins.tax, 1, 2],
      0x8a: [a.implicit, ins.txa, 1, 2],
      0xca: [a.implicit, ins.dex, 1, 2],
      0xe8: [a.implicit, ins.inx, 1, 2],
      0xa8: [a.implicit, ins.tay, 1, 2],
      0x98: [a.implicit, ins.tya, 1, 2],
      0x88: [a.implicit, ins.dey, 1, 2],
      0xc8: [a.implicit, ins.iny, 1, 2],
      0x2a: [a.accumulator, ins.rol, 1, 2],
      0x26: [a.zeroPage, ins.rol, 2, 5],
      0x36: [a.zeroPageX, ins.rol, 2, 6],
      0x2e: [a.absolute, ins.rol, 3, 6],
      0x3e: [a.absoluteX, ins.rol, 3, 7],
      0x6a: [a.accumulator, ins.ror, 1, 2],
      0x66: [a.zeroPage, ins.ror, 2, 5],
      0x76: [a.zeroPageX, ins.ror, 2, 6],
      0x6e: [a.absolute, ins.ror, 3, 6],
      0x7e: [a.absoluteX, ins.ror, 3, 7],
      0x40: [a.implicit, ins.rti, 1, 6],
      0x60: [a.implicit, ins.rts, 1, 6],
      0xe9: [a.immediate, ins.sbc, 2, 2],
      0xe5: [a.zeroPage, ins.sbc, 2, 3],
      0xf5: [a.zeroPageX, ins.sbc, 2, 4],
      0xed: [a.absolute, ins.sbc, 3, 4],
      0xfd: [a.absoluteX, ins.sbc, 3, 4],
      0xf9: [a.absoluteY, ins.sbc, 3, 4],
      0xe1: [a.indirectX, ins.sbc, 2, 6],
      0xf1: [a.indirectY, ins.sbc, 2, 5],
      0x85: [a.zeroPage, ins.sta, 2, 3],
      0x95: [a.zeroPageX, ins.sta, 2, 4],
      0x8d: [a.absolute, ins.sta, 3, 4],
      0x9d: [a.absoluteX, ins.sta, 3, 5],
      0x99: [a.absoluteY, ins.sta, 3, 5],
      0x81: [a.indirectX, ins.sta, 2, 6],
      0x91: [a.indirectY, ins.sta, 2, 6],
      0x9a: [a.implicit, ins.txs, 1, 2],
      0xba: [a.implicit, ins.tsx, 1, 2],
      0x48: [a.implicit, ins.pha, 1, 3],
      0x68: [a.implicit, ins.pla, 1, 4],
      0x08: [a.implicit, ins.php, 1, 3],
      0x28: [a.implicit, ins.plp, 1, 4],
      0x86: [a.zeroPage, ins.stx, 2, 3],
      0x96: [a.zeroPageY, ins.stx, 2, 4],
      0x8e: [a.absolute, ins.stx, 3, 4],
      0x84: [a.zeroPage, ins.sty, 2, 3],
      0x94: [a.zeroPageX, ins.sty, 2, 4],
      0x8c: [a.absolute, ins.sty, 3, 4]
    };
  }
  getOperationsbyCode(int code) {
    var operations = _table[code];
    if (operations == null) {
      throw 'Opcode invalid: $code';
    }
    return operations;
  }
}
